export const cardsData = [
  {
    type: "write",
    title: "Art History Essay",
    description: "Discuss the impact of the Renaissance on modern art. Provide examples of artists or artworks that reflect this influence.",
    imageUrl: "/cristiano.jpg",
  },
  {
    type: "multipleChoice",
    title: "Basketball Legends",
    description: "Which player is known for scoring 81 points in a single NBA game?",
    options: ["Michael Jordan", "LeBron James", "Kobe Bryant"],
    imageUrl: "/cristiano.jpg",
  },
  {
    type: "fillInTheBlank",
    title: "Capital Cities",
    description: "The capital of Italy is _____.",
    options: ["Rome", "Milan", "Naples"],
  },
  {
    type: "multipleChoice",
    title: "Formula 1 Champions",
    description: "Who holds the record for the most Formula 1 World Championships?",
    options: ["Michael Schumacher", "Lewis Hamilton", "Ayrton Senna"],
    imageUrl: "/cristiano.jpg",
  },
  {
    type: "speaking",
    title: "Geography Challenge",
    description: "Name three countries in South America and their capitals.",
  },
  {
    type: "multipleChoice",
    title: "World History",
    description: "Which event started World War II?",
    options: ["Assassination of Archduke Franz Ferdinand", "Invasion of Poland", "Bombing of Pearl Harbor"],
    //imageUrl: "/cristiano.jpg",
  },
  {
    type: "write",
    title: "Soccer Strategy",
    description: "Explain the importance of the 4-3-3 formation in modern soccer tactics.",
    imageUrl: "/cristiano.jpg",
  },
  {
    type: "listening",
    title: "Tennis Sounds",
    description: "Listen to the audio and identify which tennis stroke is being performed.",
    options: ["Forehand", "Backhand", "Serve"],
    audioUrl: "/cristiano.mp3",
  },
  {
    type: "fillInTheBlank",
    title: "Italian Language",
    description: "Translate to Italian: 'Good morning.'",
    options: ["Buongiorno", "Buonasera", "Buonanotte"],
  },
  {
    type: "matchingPairs",
    title: "Art Movements",
    description: "Match the art movements with their characteristics.",
    pairs: [
      { left: "Impressionism", right: "Light and Color" },
      { left: "Cubism", right: "Geometric Forms" },
      { left: "Surrealism", right: "Dreamlike Imagery" },
    ],
  },
  {
    type: "write",
    title: "Famous Capitals",
    description: "Describe a visit to Paris, focusing on its landmarks and cultural significance.",
    imageUrl: "/cristiano.jpg",
  },
  {
    type: "multipleChoice",
    title: "Formula 1 Circuits",
    description: "Which circuit is known as 'The Home of British Motor Racing'?",
    options: ["Silverstone", "Monaco", "Spa-Francorchamps"],
    imageUrl: "/cristiano.jpg",
  },
  {
    type: "speaking",
    title: "Geography Recital",
    description: "Recite the names of all the continents.",
  },
  {
    type: "multipleChoice",
    title: "Soccer World Cup",
    description: "Which country has won the most FIFA World Cup titles?",
    options: ["Brazil", "Germany", "Argentina"],
    imageUrl: "/cristiano.jpg",
  },
  {
    type: "fillInTheBlank",
    title: "Tennis Champions",
    description: "Roger Federer has won a record number of ____ Wimbledon titles.",
    options: ["7", "8", "9"],
  },
  {
    type: "listening",
    title: "Italian Vocabulary",
    description: "Listen to the audio and choose the correct translation.",
    options: ["Hello", "Goodbye", "Please"],
    audioUrl: "/cristiano.mp3",
  },
  {
    type: "multipleChoice",
    title: "Geography Quiz",
    description: "Which river is the longest in the world?",
    options: ["Amazon", "Nile", "Yangtze"],
    imageUrl: "/cristiano.jpg",
  },
  {
    type: "write",
    title: "Art Analysis",
    description: "Analyze the use of color in Vincent van Gogh's 'Starry Night.'",
    imageUrl: "/cristiano.jpg",
  },
  {
    type: "multipleChoice",
    title: "F1 Facts",
    description: "Which Formula 1 driver is known as 'The Flying Finn'?",
    options: ["Kimi Räikkönen", "Mika Häkkinen", "Valtteri Bottas"],
    imageUrl: "/cristiano.jpg",
  },
  {
    type: "matchingPairs",
    title: "Soccer Stars and Clubs",
    description: "Match the soccer players with the clubs they are most famous for.",
    pairs: [
      { left: "Lionel Messi", right: "Barcelona" },
      { left: "Cristiano Ronaldo", right: "Real Madrid" },
      { left: "Pelé", right: "Santos" },
    ],
  },
];
