export const cardsData = [
    {
      type: "write",
      title: "Creative Writing",
      description: "Write a short story that begins with: 'The night was cold, and the wind howled through the trees...'",
      imageUrl: "/images/night.jpg",
    },
    {
      type: "multipleChoice",
      title: "Geography Quiz",
      description: "Which of the following is the largest continent by land area?",
      options: ["Africa", "Asia", "North America"],
      imageUrl: "/images/continent.jpg",
    },
    {
      type: "listening",
      title: "Identify the Sound",
      description: "Listen to the sound and select what you hear.",
      options: ["Cat", "Dog", "Bird"],
      audioUrl: "/audio/sound1.mp3",
    },
    {
      type: "speaking",
      title: "Pronunciation Practice",
      description: "Say the following sentence out loud: 'She sells seashells by the seashore.'",
    },
    {
      type: "fillInTheBlank",
      title: "Complete the Sentence",
      description: "Fill in the blank: 'The quick brown ____ jumps over the lazy dog.'",
      options: ["fox", "dog", "cat"],
    },
    {
      type: "matchingPairs",
      title: "Match the Pairs",
      description: "Match the words with their correct translations.",
      pairs: [
        { left: "cat", right: "gato" },
        { left: "chicken", right: "gallina" },
        { left: "horse", right: "caballo" },
        { left: "dog", right: "perro" },
        { left: "bird", right: "pájaro" },
      ],
    },
    {
      type: "write",
      title: "Philosophical Thought",
      description: "What does 'the meaning of life' mean to you?",
      imageUrl: "/images/philosophy.jpg",
    },
    {
      type: "multipleChoice",
      title: "Science Trivia",
      description: "What is the chemical symbol for gold?",
      options: ["Au", "Ag", "Pt"],
    },
    {
      type: "write",
      title: "Personal Reflection",
      description: "Describe a moment in your life that changed you forever.",
    },
    {
      type: "reading",
      title: "Reading Comprehension",
      description: "Read the passage and answer the questions.",
      passage: "The sun rises in the east and sets in the west. This daily cycle is known as a day.",
      questions: [
        { question: "Where does the sun rise?", options: ["East", "West"] },
        { question: "What is this cycle called?", options: ["Day", "Night"] },
      ],
    },
    {
      type: "multipleChoice",
      title: "Historical Knowledge",
      description: "Who was the first president of the United States?",
      options: ["George Washington", "Thomas Jefferson", "Abraham Lincoln"],
      imageUrl: "/images/president.jpg",
    },
    {
      type: "write",
      title: "Travel Dreams",
      description: "If you could visit any place in the world, where would it be and why?",
      imageUrl: "/images/travel.jpg",
    },
    {
      type: "multipleChoice",
      title: "Literary Analysis",
      description: "Which of these authors wrote '1984'?",
      options: ["George Orwell", "Aldous Huxley", "Ray Bradbury"],
    },
    {
      type: "speaking",
      title: "Speech Practice",
      description: "Recite the following phrase: 'The early bird catches the worm.'",
    },
    {
      type: "listening",
      title: "Music Identification",
      description: "Listen to the music clip and identify the genre.",
      options: ["Jazz", "Classical", "Rock"],
      audioUrl: "/audio/music1.mp3",
    },
    {
      type: "write",
      title: "Future Goals",
      description: "What are your top three goals for the next five years?",
    },
    {
      type: "multipleChoice",
      title: "Music Appreciation",
      description: "Which of the following is a song by The Beatles?",
      options: ["Hey Jude", "Bohemian Rhapsody", "Hotel California"],
      imageUrl: "/images/music.jpg",
    },
    {
      type: "fillInTheBlank",
      title: "Language Learning",
      description: "Complete the sentence: 'Yo ____ a la escuela todos los días.'",
      options: ["voy", "van", "vas"],
    },
    {
      type: "matchingPairs",
      title: "Match the Capitals",
      description: "Match the countries with their capitals.",
      pairs: [
        { left: "France", right: "Paris" },
        { left: "Germany", right: "Berlin" },
        { left: "Japan", right: "Tokyo" },
      ],
    },
    {
      type: "listening",
      title: "Identify the Instrument",
      description: "Listen to the sound and identify the instrument.",
      options: ["Piano", "Violin", "Guitar"],
      audioUrl: "/audio/instrument1.mp3",
    },
  ];