import Footer from "@/components/footer"
import Header from "@/components/header"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { TooltipProvider, Tooltip, TooltipTrigger, TooltipContent } from "@/components/ui/tooltip"
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet"
import { NavigationMenu, NavigationMenuList, NavigationMenuLink } from "@/components/ui/navigation-menu"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuRadioGroup, DropdownMenuRadioItem } from "@/components/ui/dropdown-menu"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { CircleHelpIcon, HomeIcon, MenuIcon, MountainIcon, SettingsIcon, UserIcon } from "lucide-react"
import { AvatarDropdownMenu } from "@/components/avatar-dropdown-menu"
import Logo from "@/components/logo"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen w-full">
          <aside className="hidden w-56 flex-col border-r bg-background p-4 md:flex">
            <nav className="flex flex-col gap-4">
              <Link
                href="/home"
                className="group flex shrink-0 items-center justify-center rounded-full bg-primary text-lg font-semibold text-primary-foreground"
                prefetch={false}
              >
                Chop Inc.
              </Link>
              <Link
                href="/home"
                className="flex items-center  rounded-lg text-muted-foreground transition-colors hover:text-foreground gap-2"
                prefetch={false}
              >
                <HomeIcon className="h-5 w-5" />
                <span className="">Home</span>
              </Link>
              <Link
                href="/profile"
                className="flex items-center rounded-lg bg-accent text-accent-foreground transition-colors hover:text-foreground p-2 gap-2"
                prefetch={false}
              >
                <UserIcon className="h-5 w-5" />
                <span className="">Profile</span>
              </Link>
              <Link
                href="/settings"
                className="flex items-center rounded-lg text-muted-foreground transition-colors hover:text-foreground"
                prefetch={false}
              >
                <SettingsIcon className="h-5 w-5" />
                <span>Settings</span>
              </Link>
            </nav>
            <nav className="mt-auto flex flex-col gap-4">
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Link
                      href="#"
                      className="flex items-center rounded-lg text-muted-foreground transition-colors hover:text-foreground"
                      prefetch={false}
                    >
                      <CircleHelpIcon className="h-5 w-5" />
                      <span>Support</span>
                    </Link>
                  </TooltipTrigger>
                  <TooltipContent side="right">Support</TooltipContent>
                </Tooltip>
              </TooltipProvider>
            </nav>
          </aside>
          <div className="flex flex-1 flex-col">
            <header className="sticky top-0 z-30 flex h-14 items-center gap-4 border-b bg-background px-4 md:static md:h-auto md:border-0 md:bg-transparent md:px-6">
              <Sheet>
                <SheetTrigger asChild>
                  <Button size="icon" variant="outline" className="md:hidden">
                    <MenuIcon className="h-5 w-5" />
                    <span className="sr-only">Toggle Menu</span>
                  </Button>
                </SheetTrigger>
                <SheetContent side="left" className="md:max-w-xs">
                  <nav className="grid gap-6 text-lg font-medium">
                    <Link
                      href="/"
                      className="group flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary text-lg font-semibold text-primary-foreground"
                      prefetch={false}
                    >
                      <MountainIcon className="h-5 w-5 transition-all group-hover:scale-110" />
                      <span className="sr-only">Chop Inc</span>
                    </Link>
                    <Link
                      href="/home"
                      className="flex items-center gap-4 px-2.5 text-muted-foreground hover:text-foreground"
                      prefetch={false}
                    >
                      <HomeIcon className="h-5 w-5" />
                      Home
                    </Link>
                    <Link href="/profile" className="flex items-center gap-4 px-2.5 text-foreground" prefetch={false}>
                      <UserIcon className="h-5 w-5" />
                      Profile
                    </Link>
                    <Link
                      href="/settings"
                      className="flex items-center gap-4 px-2.5 text-muted-foreground hover:text-foreground"
                      prefetch={false}
                    >
                      <SettingsIcon className="h-5 w-5" />
                      Settings
                    </Link>
                  </nav>
                </SheetContent>
              </Sheet>
              <div className="ml-auto flex items-center gap-2">
                <AvatarDropdownMenu />
              </div>
            </header>
            <main className="flex-1 p-4 md:p-6">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  )
}